config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'tags', to: 'tags#index', as: 'tags'

  get 'sync/feeds'
  get 'opml/import'
  post 'opml/import', to: 'opml#importer', as: 'opml_importer'

  get 'notes/tagged/:id', to: 'tags#show_notes', as: 'show_notes_tagged'

  get 'entries/starred', to: 'entries#starred', as: 'starred_entries'
  get 'entries/tagged/:id/all', to: 'tags#all_entries', as: 'all_entries_tagged'
  get 'entries/tagged/:id', to: 'tags#show_entries', as: 'show_entries_tagged'

  get 'entries/:id', to: 'entries#show', as: 'entry'
  get 'entries/:id/read', to: 'entries#read', as: 'read_entry'
  get 'entries/:id/unread', to: 'entries#unread', as: 'unread_entry'
  get 'entries/:id/star', to: 'entries#star', as: 'star_entry'

  get 'sync/feeds', to: 'sync#feeds', as: 'feeds_sync'
  resources :feeds

  resources :notes, except: [:destroy]

  root to: 'news#index'
end

app/models/note.rb
# frozen_string_literal: true

# A note
class Note < ApplicationRecord
  acts_as_taggable_on :tags
  has_paper_trail

  scope :tagged, lambda { |tag|
    tagged_with(tag)
  }

  class << self
    def group_by_day(notes)
      data = []
      notes.each do |e|
        date = e.updated_at.strftime('%Y-%m-%d')
        data << { date: date, entries: [] } unless date_match?(data.last, date)
        data.last[:entries] << e
      end
      data
    end

    private

    def date_match?(data, date)
      !data.nil? && data[:date] == date
    end
  end

end

app/controllers/notes_controller.rb
# frozen_string_literal: true

# Notes controller
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update]

  def index
    @notes = Note.all
  end

  def show; end

  def new
    @note = Note.new
  end

  def edit; end

  def create
    @note = Note.new(note_params)

    if @note.save
      redirect_to @note, notice: 'Note was successfully created.'
    else
      render :new
    end
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :content, :tag_list)
  end
end

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing <%= @note.title %></h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<ul class='entry_list'>
  <% @notes.each do |n| %>
    <li>
      <h2><%= link_to n.title, n %></h2>
      <div><%= to_html(n.content[0..250]) %></div>
    </li>
  <% end %>
</ul>

<br />

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<main id='note'>
  <h1><%= @note.title %></h1>
  <% unless @note.tags.empty? %>
    <small><strong>Tags:</strong>
      <% @note.tags.each do |t| %>
        <%= link_to t.name, show_tag_url(t.name) %>
      <% end %>
    </small>
  <% end %>

  <div class='content'><%= to_html(@note.content) %></div>

  <%= link_to 'Edit', edit_note_path(@note) %> |
  <%= link_to 'Back', notes_path %>
</main>