config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'tags', to: 'tags#index', as: 'tags'

  get 'sync/feeds'
  get 'opml/import'
  post 'opml/import', to: 'opml#importer', as: 'opml_importer'

  get 'notes/tagged/:id', to: 'tags#show_notes', as: 'show_notes_tagged'

  get 'entries/starred', to: 'entries#starred', as: 'starred_entries'
  get 'entries/tagged/:id/all', to: 'tags#all_entries', as: 'all_entries_tagged'
  get 'entries/tagged/:id', to: 'tags#show_entries', as: 'show_entries_tagged'

  get 'entries/:id', to: 'entries#show', as: 'entry'
  get 'entries/:id/read', to: 'entries#read', as: 'read_entry'
  get 'entries/:id/unread', to: 'entries#unread', as: 'unread_entry'
  get 'entries/:id/star', to: 'entries#star', as: 'star_entry'

  get 'sync/feeds', to: 'sync#feeds', as: 'feeds_sync'
  resources :feeds

  resources :notes, except: [:destroy]

  root to: 'news#index'
end

app/models/feed.rb
# frozen_string_literal: true

require 'net/https'
require 'uri'

# An individual feed
class Feed < ApplicationRecord
  validates :feed_url, presence: true, uniqueness: true

  has_many :entries, dependent: :destroy, autosave: true

  acts_as_taggable_on :tags

  before_validation :update_entry_tags_if_needed

  REDIRECTS = [301, 302, 307, 308].freeze

  def unread_count
    entries.where(read: false).count
  end

  def force_sync!
    self.etag = nil
    self.last_modified = nil
    resp = sync
    save!

    resp
  end

  def sync
    resp = fetch(URI.parse(feed_url))
    return handle_redirect(resp['location']) if REDIRECTS.include?(resp.code.to_i)
    return 'no-update' if resp.code.to_i == 304

    if resp.code.to_i != 200
      Rails.logger.error("check result #{resp.code}")
      return 'fail'
    end

    process_feed(resp)
  end

  private

  def update_entry_tags_if_needed
    return unless tag_list_changed?

    entries.each do |e|
      e.tag_list.add(tag_list)
      e.save
    end
  end

  # TODO(dj2): May want to limit the depth it will follow here in case there
  #            is a loop.
  def handle_redirect(loc)
    self.feed_url = if loc.starts_with?('/')
                      uri = URI.parse(feed_url)
                      uri.path = loc
                      uri.to_s
                    else
                      loc
                    end
    sync
  end

  def fetch(uri)
    headers = { 'User-Agent' => 'Syn 0.0.1' }

    http = Net::HTTP.new(uri.host, uri.port)
    setup_ssl(http) if uri.port == 443

    headers['If-None-Match'] = etag if etag.present?
    headers['If-Modified-since'] = last_modified if last_modified.present?

    http.request(Net::HTTP::Get.new(uri.request_uri, headers))
  end

  def setup_ssl(http)
    http.verify_mode = OpenSSL::SSL::VERIFY_PEER
    http.use_ssl = true
  end

  def known_content_type?(name)
    name =~ %r{text/xml} ||
      name =~ %r{text/plain} ||
      name =~ %r{application/atom\+xml} ||
      name =~ %r{application/rss\+xml} ||
      name =~ %r{application/xml}
  end

  def update_fetch_settings(resp)
    self.etag = resp['etag']
    self.last_modified = resp['last-modified']
    self.last_updated = Time.zone.now
  end

  def process_feed(resp)
    update_fetch_settings(resp)

    type = resp['content-type']
    return "unknown-content-type #{type}" unless known_content_type?(type)

    result = FeedParser.parse(resp.body)

    self.name = result[:name]
    self.description = result[:description]
    self.site_url = result[:site_url]

    result[:entries].each { |e| process_entry(e) }
    'ok'
  end

  def process_entry(data)
    return if Entry.where(guid: data[:guid]).present?

    entry = Entry.new(data)
    entry.tag_list = tag_list
    entries << entry
  end
end

app/controllers/feeds_controller.rb
# frozen_string_literal: true

# Controller for interacting with feeds.
class FeedsController < ApplicationController
  before_action :set_feed, only: %i[show edit update destroy]

  def index
    @feeds = Feed.all.order(:name)
  end

  def show; end

  def new
    @feed = Feed.new
  end

  def edit; end

  def create
    @feed = Feed.new(feed_params)

    if @feed.save
      redirect_to @feed, notice: 'Feed was successfully created.'
    else
      render :new
    end
  end

  def update
    if @feed.update(feed_params)
      redirect_to @feed, notice: 'Feed was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @feed.destroy
    redirect_to feeds_url, notice: 'Feed was successfully destroyed.'
  end

  private

  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:feed_url, :tag_list)
  end
end

app/views/feeds/_form.html.erb
<%= form_with(model: feed) do |form| %>
  <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
        <% feed.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :feed_url %>
    <%= form.text_field :feed_url %>
  </div>

  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feeds</h1>

<ul>
  <% @feeds.each do |feed| %>
    <li><%= link_to feed.name, feed %> : <%= feed.unread_count %> unread</li>
  <% end %>
</ul>

<br>

<%= link_to 'New Feed', new_feed_path %>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form', feed: @feed %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= link_to @feed.name, @feed.site_url %></h1>
<h2><%= @feed.description %></h2>
<small><%= link_to @feed.feed_url, @feed.feed_url %></small><br />
<% unless @feed.tags.empty? %>
  <small><strong>Tags</strong>:
    <% @feed.tags.each do |t| %>
      <%= link_to t.name, show_entries_tagged_url(t.name) %>
    <% end %>
  </small>
<% end %>

<p>
  <strong>Last updated:</strong>
  <%= @feed.last_updated %>
</p>

<ul class='entry_list'>
  <% @feed.entries.order(published_date: :desc).each do |e| %>
    <li>
      <h2><%= link_to e.title, e %></h2>
      <small><%= e.published_date %></small>
      <div><%= to_html(e.content[0..250]) %></div>
    </li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>