config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'tags', to: 'tags#index', as: 'tags'

  get 'sync/feeds'
  get 'opml/import'
  post 'opml/import', to: 'opml#importer', as: 'opml_importer'

  get 'notes/tagged/:id', to: 'tags#show_notes', as: 'show_notes_tagged'

  get 'entries/starred', to: 'entries#starred', as: 'starred_entries'
  get 'entries/tagged/:id/all', to: 'tags#all_entries', as: 'all_entries_tagged'
  get 'entries/tagged/:id', to: 'tags#show_entries', as: 'show_entries_tagged'

  get 'entries/:id', to: 'entries#show', as: 'entry'
  get 'entries/:id/read', to: 'entries#read', as: 'read_entry'
  get 'entries/:id/unread', to: 'entries#unread', as: 'unread_entry'
  get 'entries/:id/star', to: 'entries#star', as: 'star_entry'

  get 'sync/feeds', to: 'sync#feeds', as: 'feeds_sync'
  resources :feeds

  resources :notes, except: [:destroy]

  root to: 'news#index'
end

app/models/entry.rb
# frozen_string_literal: true

# An individual feed entry
class Entry < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true, uniqueness: true
  validates :guid, presence: true, uniqueness: true

  belongs_to :feed

  acts_as_taggable_on :tags

  default_scope { order(published_date: :desc) }

  scope :starred, lambda {
    where(starred: true)
      .includes(:feed)
  }

  scope :unread, lambda {
    where(read: false)
      .includes(%i[feed tags])
  }

  scope :tagged, lambda { |tag|
    tagged_with(tag)
      .includes(%i[feed tags])
  }

  class << self
    def group_by_day(entries)
      data = []
      entries.each do |e|
        date = e.published_date.strftime('%Y-%m-%d')
        data << { date: date, entries: [] } unless date_match?(data.last, date)
        data.last[:entries] << e
      end
      data
    end

    private

    def date_match?(data, date)
      !data.nil? && data[:date] == date
    end
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

# Controller for interacting with feed entries
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[show star read unread]

  def starred
    @entries = Entry.starred
  end

  def show
    return if @entry.read

    @entry.read = true
    @entry.save
  end

  def read
    @entry.read = true
    @entry.save
    render json: 'ok'
  end

  def unread
    if @entry.read?
      @entry.read = false
      @entry.save
    end
    render :show
  end

  def star
    @entry.starred = !@entry.starred
    @entry.save
    redirect_to entry_url(@entry)
  end

  private

  def set_entry
    @entry = Entry.find(params[:id])
  end
end

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<article class='post'>
  <h1><%= @entry.title %></h1>
  <small><%= link_to @entry.url, @entry.url %></small><br />
  <small><%= @entry.published_date %></small><br />
  <small><strong>Feed</strong>: <%= link_to @entry.feed.name, @entry.feed %></small><br />

  <% unless @entry.tags.empty? %>
    <small><strong>Tags:</strong>
      <% @entry.tags.each do |t| %>
        <%= link_to t.name, show_entries_tagged_url(t.name) %>
      <% end %>
    </small>
  <% end %>

  <div class='content'><%= to_html(@entry.content) %></div>

  <% if @entry.read %>
    <%= link_to 'Mark unread', unread_entry_path(@entry) %> |
  <% else %>
    <%= link_to 'Mark read', entry_path(@entry) %> |
  <% end %>

  <%= link_to @entry.starred? ? 'Unstar' : 'star', star_entry_path(@entry) %> |
  <%= link_to 'Back', feed_path(@entry.feed) %>
</article>

app/views/entries/starred.html.erb
<ul id='entry_list'>
  <% @entries.each do |e| %>
    <li>
      <%= link_to "#{e.feed.name}: #{e.title}", entry_url(e) %> --
      <%= e.published_date %>
    </li>
  <% end %>
</ul>